meta_product_name: "flyinvite"
meta_title: "flyinvite - business travel made simple"
meta_description: "flyinvite allows event organizers to organize trips, and travellers to pick their flights."
meta_image: "cover.png" # should exist in `app/assets/images/`